export { default as themeReducer } from "./themeSlice"
export { default as bannerReducer } from "./bannerSlice"
export { default as lectureReducer } from "./lectureSlice"
export { default as settingReducer } from "./settingSlice"
export { default as userReducer } from "./userSlice"
